export const ADD_MOVIE = 'ADD_MOVIE';
export const SET_MOVIES = 'SET_MOVIES'
export const SET_SERIES = 'SET_SERIES'
export const SHOW_MOVIES_LISTITEMS = 'SHOW_MOVIES_LISTITEMS'
export const SHOW_SERIES_LISTITEMS = 'SHOW_SERIES_LISTITEMS'

